### ISSUE TITLE
NoneType object not iterable when using spotifyd

### ISSUE THREAD

**Issue by extremepayne** [ceuk/spotui#12]
Just started `spotifyd`, got this new error:
```python
Traceback (most recent call last):
  File "spotui", line 8, in <module>
    sys.exit(main())
  File "/home/harrison/.local/lib/python3.8/site-packages/spotui/__main__.py", line 6, in main
    SpoTUI = curses.wrapper(App)
  File "/usr/lib/python3.8/curses/__init__.py", line 105, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/harrison/.local/lib/python3.8/site-packages/spotui/src/ui.py", line 8, in __init__
    self.main_form = MainForm(stdscr)
  File "/home/harrison/.local/lib/python3.8/site-packages/spotui/src/MainForm.py", line 51, in __init__
    PlaylistMenu(stdscr, self.api, self.change_tracklist),
  File "/home/harrison/.local/lib/python3.8/site-packages/spotui/src/PlaylistMenu.py", line 15, in __init__
    self.restart()
  File "/home/harrison/.local/lib/python3.8/site-packages/spotui/src/PlaylistMenu.py", line 26, in restart
    list(map(self.__map_playlists, self.items)),
TypeError: 'NoneType' object is not iterable
```
Error persists eve after stopping `spotifyd` and/or un-and re-installing `spotui` library.
**Desktop:**
 - OS: Linux
 - Version SpoTUI 0.1.10

**Comment by extremepayne** [comment]
It went away by itself and I couldn't reproduce again. I'll close and if it happens again, I'll be back with more info.
