### ISSUE TITLE
Crash upon providing URL

### ISSUE THREAD

**Issue by zeroeightysix** [ceuk/spotui#2]
**Describe the bug**
Spotui crashes after configuring and providing the 'broken link'

**To Reproduce**
1. Install spotui
2. Configure `.spotuirc`
3. Launch spotui and provide the link you were redirected to
4. Spotui crashes

**Stack trace**
```
Traceback (most recent call last):
  File "/usr/bin/spotui", line 6, in <module>
    from spotui.__main__ import main
  File "/usr/lib/python3.8/site-packages/spotui/__main__.py", line 2, in <module>
    from spotui.src.ui import App
  File "/usr/lib/python3.8/site-packages/spotui/src/ui.py", line 1, in <module>
    from spotui.src.MainForm import MainForm
  File "/usr/lib/python3.8/site-packages/spotui/src/MainForm.py", line 4, in <module>
    from spotui.src.spotifyApi import SpotifyApi
  File "/usr/lib/python3.8/site-packages/spotui/src/spotifyApi.py", line 220, in <module>
    client = SpotifyApi()
  File "/usr/lib/python3.8/site-packages/spotui/src/spotifyApi.py", line 10, in __init__
    self.auth()
  File "/usr/lib/python3.8/site-packages/spotui/src/spotifyApi.py", line 19, in auth
    self.token = util.prompt_for_user_token(
  File "/usr/lib/python3.8/site-packages/spotipy/util.py", line 86, in prompt_for_user_token
    token_info = sp_oauth.get_access_token(code)
  File "/usr/lib/python3.8/site-packages/spotipy/oauth2.py", line 217, in get_access_token
    raise SpotifyOauthError(response.reason)
spotipy.oauth2.SpotifyOauthError: Bad Request
```

**Comment by zeroeightysix** [comment]
Nevermind, I forgot to specify the callback URI on the spotify developer dashboard! Maybe this should be added more clearly to the README / default configuration file.
