### ISSUE TITLE
TypeError raised when no songs have yet been played

### ISSUE THREAD

**Issue by extremepayne** [ceuk/spotui#5]
**Describe the bug**
When selecting "recently played" and nothing has yet been played (due to an inablility to play any tracks; I'm working on debugging it since it might actually be my fault, idk, if not, I'll submit a report shortly) the program craashes with the a TypeError.
```
❯ python3 spotui
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "spotui/__main__.py", line 10, in <module>
    main()
  File "spotui/__main__.py", line 6, in main
    SpoTUI = curses.wrapper(App)
  File "/usr/lib/python3.5/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/user/.local/lib/python3.5/site-packages/spotui/src/ui.py", line 8, in __init__
    self.main_form = MainForm(stdscr)
  File "/home/user/.local/lib/python3.5/site-packages/spotui/src/MainForm.py", line 98, in __init__
    key)
  File "/home/user/.local/lib/python3.5/site-packages/spotui/src/LibraryMenu.py", line 61, in receive_input
    self.items[self.component.selected]["handler"]()
  File "/home/user/.local/lib/python3.5/site-packages/spotui/src/LibraryMenu.py", line 54, in __select_recent_tracks
    "Recently Played")
  File "/home/user/.local/lib/python3.5/site-packages/spotui/src/MainForm.py", line 123, in change_tracklist
    self.components[0].update_tracks(tracks, title)
  File "/home/user/.local/lib/python3.5/site-packages/spotui/src/TracksMenu.py", line 30, in update_tracks
    self.items = list(map(self.__map_tracks, tracks))
TypeError: 'NoneType' object is not iterable
```
**To Reproduce**
1. Fresh install
2. `python3 spotui` in `~/.local/lib/python3.5/site-packages`
3. Don't play any tracks
4. Select "Recently played"

**Expected behavior**
The program should fail gracefully. 

**Desktop (please complete the following information):**
 - OS: ChromeOS 79 with Debian Stretch VM (via native "linux (beta)" feature)
- Browser: Chrome 79

**Additional context**
I think that covers it.

**Comment by extremepayne** [comment]
I got a similar error trying to select a device when none were available. I know, I know, I'm so dumb, pressing enter on things I logically shouldn't, but the program could really benefit from a bit of this:
```
if devices:
    # do stuff
else:
    # fail gracefully (i.e. display "No devices" and ignore all input except escape)
```

**Comment by ceuk** [comment]
Hey @extremepayne 

I'm unable to get Recently Played to be blank on mine but I think the if statement alterations in 8f00622 should fix it :crossed_fingers: Would you mind confirming when you get a sec?

**Comment by extremepayne** [comment]
That seems to have done it. Thanks for the quick fix! I `pip install --upgrade`d and it no longer fails. I was unable to reproduce the other bug so I'll close.

(Edit: I looked at some other issues and it looks like someone else reported the other error and you fixed it, so good job!)
